/*
 * SPDX-FileCopyrightText: Copyright Corsinvest Srl
 * SPDX-License-Identifier: MIT
 */

namespace Corsinvest.Fx.Functional.Tests;

/// <summary>
/// Locks the public shape of Option and ResultOf after the move to the IUnion marker.
/// </summary>
public class UnionCoreTypesTests
{
    [Fact]
    public void Option_Some_CarriesTheValue()
    {
        var option = Option.Some(42);

        Assert.True(option.IsSome);
        Assert.Equal(42, option.Match(some => some.Value, none => 0));
    }

    [Fact]
    public void Option_None_IsRecognised()
    {
        var option = Option.None<int>();

        Assert.True(option.IsNone);
        Assert.Equal(0, option.Match(some => some.Value, none => 0));
    }

    [Fact]
    public void Option_SupportsNativeSwitch()
    {
        Option<int> option = Option.Some(7);

        var result = option switch
        {
            Option<int>.Some(var some) => some.Value,
            Option<int>.None => 0
        };

        Assert.Equal(7, result);
    }

    [Fact]
    public void Option_Map_StillChains()
    {
        Assert.Equal(10, Option.Some(5).Map(x => x * 2).GetValueOr(0));
    }

    [Fact]
    public void ResultOf_Ok_CarriesTheValue()
    {
        var result = ResultOf.Ok<int, string>(42);

        Assert.True(result.IsOk);
        Assert.True(result.IsSuccess);
        Assert.Equal(42, result.Match(ok => ok.Value, fail => 0));
    }

    [Fact]
    public void ResultOf_Fail_CarriesTheError()
    {
        var result = ResultOf.Fail<int, string>("boom");

        Assert.True(result.IsFail);
        Assert.True(result.IsFailure);
        Assert.Equal("boom", result.Match(ok => "", fail => fail.ErrorValue));
    }

    [Fact]
    public void ResultOf_SupportsNativeSwitch()
    {
        ResultOf<int, string> result = ResultOf.Ok<int, string>(7);

        var value = result switch
        {
            ResultOf<int, string>.Ok(var ok) => ok.Value,
            ResultOf<int, string>.Fail => -1
        };

        Assert.Equal(7, value);
    }

    [Fact]
    public void ResultOf_BindStillShortCircuits()
    {
        var result = ResultOf.Ok<int, string>(1)
                             .Bind(x => ResultOf.Fail<int, string>("stop"))
                             .Bind(x => ResultOf.Ok<int, string>(x + 1));

        Assert.Equal("stop", result.Match(ok => "", fail => fail.ErrorValue));
    }

    // ============================================
    // MatchAsync overloads on ResultOf<T,E> and Task<ResultOf<T,E>> - generated by UnionGenerator
    // (GenerateMatch's void MatchAsync, GenerateUnionExtensions' ResultOfUnionExtensions) since
    // Task 6 restored them; previously a hand-written TEMPORARY region in ResultOfExtensions.cs,
    // now deleted. Every overload must reach the correct handler for both cases; see
    // ResultOf_InvalidUnionState_CannotBeConstructed for why the throw-on-default arm isn't
    // independently testable.
    // ============================================

    [Fact]
    public async Task ResultOf_InstanceVoidMatchAsync_ReachesOkHandler()
    {
        var result = ResultOf.Ok<int, string>(42);
        var okReached = false;
        var failReached = false;

        await result.MatchAsync(
            async ok => { await Task.Delay(1); okReached = true; },
            async fail => { await Task.Delay(1); failReached = true; }
        );

        Assert.True(okReached);
        Assert.False(failReached);
    }

    [Fact]
    public async Task ResultOf_InstanceVoidMatchAsync_ReachesFailHandler()
    {
        var result = ResultOf.Fail<int, string>("boom");
        var okReached = false;
        var failReached = false;

        await result.MatchAsync(
            async ok => { await Task.Delay(1); okReached = true; },
            async fail => { await Task.Delay(1); failReached = true; }
        );

        Assert.False(okReached);
        Assert.True(failReached);
    }

    [Fact]
    public async Task ResultOf_TaskMatchAsync_AsyncValueHandlers_ReachesBothCases()
    {
        var okTask = Task.FromResult(ResultOf.Ok<int, string>(42));
        var failTask = Task.FromResult(ResultOf.Fail<int, string>("boom"));

        var okValue = await okTask.MatchAsync(
            async ok => { await Task.Delay(1); return ok.Value; },
            async fail => { await Task.Delay(1); return -1; }
        );
        var failValue = await failTask.MatchAsync(
            async ok => { await Task.Delay(1); return ""; },
            async fail => { await Task.Delay(1); return fail.ErrorValue; }
        );

        Assert.Equal(42, okValue);
        Assert.Equal("boom", failValue);
    }

    [Fact]
    public async Task ResultOf_TaskMatchAsync_AsyncVoidHandlers_ReachesBothCases()
    {
        var okTask = Task.FromResult(ResultOf.Ok<int, string>(42));
        var failTask = Task.FromResult(ResultOf.Fail<int, string>("boom"));
        var okReached = false;
        var failReached = false;

        await okTask.MatchAsync(
            async ok => { await Task.Delay(1); okReached = true; },
            async fail => { await Task.Delay(1); }
        );
        await failTask.MatchAsync(
            async ok => { await Task.Delay(1); },
            async fail => { await Task.Delay(1); failReached = true; }
        );

        Assert.True(okReached);
        Assert.True(failReached);
    }

    [Fact]
    public async Task ResultOf_TaskMatchAsync_SyncHandlers_ReachesBothCases()
    {
        var okTask = Task.FromResult(ResultOf.Ok<int, string>(42));
        var failTask = Task.FromResult(ResultOf.Fail<int, string>("boom"));

        var okValue = await okTask.MatchAsync(ok => ok.Value, fail => -1);
        var failValue = await failTask.MatchAsync(ok => "", fail => fail.ErrorValue);

        Assert.Equal(42, okValue);
        Assert.Equal("boom", failValue);
    }

    [Fact]
    public void ResultOf_InvalidUnionState_CannotBeConstructed()
    {
        // ResultOf<T,E> is abstract with a private constructor; only the generator's own nested
        // Ok/Fail sealed records (declared in the same generated partial) can call it. There is no
        // public-API route - no reflection, no unsafe cast - that reaches a third subtype, so the
        // `throw new InvalidOperationException("Invalid union state")` default arm in every
        // Match/MatchAsync overload (generated and hand-written alike) is unreachable dead code
        // through legitimate use. This test documents that fact rather than exercising the throw,
        // per the reviewer's instruction not to fabricate a test that cannot fail.
        //
        // The only constructors present are the generator's own private ResultOf() and the
        // compiler-synthesized protected copy constructor ResultOf(ResultOf<T,E>) that records
        // require to support `with` on their sealed derived types - neither is callable from
        // outside this type's own declaration, so nothing outside Ok/Fail can ever derive from it.
        var resultOfType = typeof(ResultOf<int, string>);
        var constructors = resultOfType.GetConstructors(System.Reflection.BindingFlags.Public
                                                        | System.Reflection.BindingFlags.NonPublic
                                                        | System.Reflection.BindingFlags.Instance);

        Assert.True(resultOfType.IsAbstract);
        Assert.DoesNotContain(constructors, ctor => ctor.IsPublic);
        Assert.All(constructors, ctor => Assert.True(ctor.IsPrivate || ctor.IsFamily));
    }

    // ============================================
    // None sharing: the allocation is gone, the semantics are not
    // ============================================

    [Fact]
    public void Option_None_ReturnsASharedInstance()
    {
        // A None carries no data, so one instance can stand in for all of them. This is the
        // allocation the sharing removes - the assertions below are what make it safe.
        Assert.Same(Option.None<int>(), Option.None<int>());
    }

    [Fact]
    public void Option_None_SharingIsNotObservable()
    {
        var a = Option.None<int>();
        var b = Option.None<int>();

        Assert.Equal(a, b);
        Assert.True(a == b);
        Assert.Equal(a.GetHashCode(), b.GetHashCode());
        Assert.Single(new HashSet<Option<int>> { a, b });
        Assert.True(a.IsNone);
        Assert.Equal("None", a.Match(some => "Some", none => "None"));
        Assert.Equal("None", a switch { Option<int>.Some => "Some", Option<int>.None => "None" });
        Assert.Equal(99, a.GetValueOr(99));
    }

    [Fact]
    public void Option_None_IsPerConstructedType()
    {
        // Option<int>.None and Option<string>.None are different types, so each gets its own
        // shared instance. A single shared None across every T would not even typecheck.
        Assert.NotSame(Option.None<int>(), (object)Option.None<string>());
    }

    // ============================================
    // Some(null): the state Option<T> exists to rule out
    // ============================================

    [Fact]
    public void Option_Some_RejectsNull()
    {
        // A Some holding null reports IsSome while carrying nothing, so the
        // NullReferenceException Option<T> was meant to prevent surfaces later, inside a Map or
        // Bind, far from where the null entered.
        var ex = Assert.Throws<ArgumentNullException>(() => Option.Some<string>(null!));
        Assert.Equal("value", ex.ParamName);
    }

    [Fact]
    public void Option_FromNullable_IsTheWayToHandleAPossibleNull()
    {
        Assert.True(Option.FromNullable<string>(null).IsNone);
        Assert.True(Option.FromNullable("value").IsSome);
    }

    [Fact]
    public void Option_Some_AcceptsAValueTypeDefault()
    {
        // default(int) is not null - rejecting it would break Some(0).
        Assert.True(Option.Some(0).IsSome);
        Assert.True(Option.Some(false).IsSome);
    }

    [Fact]
    public void Option_Some_DoesNotBoxAValueType()
    {
        // The null check must not cost an allocation on a value type, where it cannot even fail.
        // ArgumentNullException.ThrowIfNull takes object?, so using it here boxed every Some(42).
        // `value is null` compares without converting.
        //
        // The assertion is relative rather than an absolute byte count: a Debug build allocates
        // more per call than a Release one (72 B against 48 B here), so a fixed bound would either
        // fail under Debug or be too loose to catch the regression under Release. Some<string>
        // runs the same two allocations - the payload and its wrapper - but its null check is a
        // real reference comparison that never boxes, which makes it the baseline.
        const int iterations = 20_000;

        for (var i = 0; i < 2_000; i++) { _ = Option.Some(i); _ = Option.Some("x"); }

        var before = GC.GetAllocatedBytesForCurrentThread();
        for (var i = 0; i < iterations; i++) { _ = Option.Some(i); }
        var valueType = GC.GetAllocatedBytesForCurrentThread() - before;

        before = GC.GetAllocatedBytesForCurrentThread();
        for (var i = 0; i < iterations; i++) { _ = Option.Some("x"); }
        var referenceType = GC.GetAllocatedBytesForCurrentThread() - before;

        Assert.True(valueType <= referenceType,
            $"Some(int) allocated {valueType / (double)iterations:F0} B/call against "
            + $"{referenceType / (double)iterations:F0} B/call for Some(string); the excess is a boxed int");
    }
}
