using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using System.Collections.Immutable;
using System.Text;

namespace Corsinvest.Fx.Functional;

[Generator]
public class UnionGenerator : IIncrementalGenerator
{
    // Diagnostic descriptors
    private static readonly DiagnosticDescriptor UnionGenerationFailedDescriptor = new(
        id: "UNION001",
        title: "Union generation failed",
        messageFormat: "Failed to generate union for '{0}': {1}",
        category: "Generator",
        defaultSeverity: DiagnosticSeverity.Error,
        isEnabledByDefault: true);

    private static readonly DiagnosticDescriptor UnionMustBePartialDescriptor = new(
        id: "UNION002",
        title: "Union type must be partial",
        messageFormat: "Type '{0}' with [Union] attribute must be declared as 'partial'",
        category: "Design",
        defaultSeverity: DiagnosticSeverity.Error,
        isEnabledByDefault: true);

    private static readonly DiagnosticDescriptor VariantMustBePartialDescriptor = new(
        id: "UNION003",
        title: "Union variant must be partial",
        messageFormat: "Variant '{0}' in union '{1}' must be declared as 'partial record'",
        category: "Design",
        defaultSeverity: DiagnosticSeverity.Error,
        isEnabledByDefault: true);

    private static readonly DiagnosticDescriptor CaseNameCollisionDescriptor = new(
        id: "UNION008",
        title: "Union case names collide",
        messageFormat: "Union '{0}' has case types that resolve to the same wrapper name; "
                     + "use [UnionCaseName<T>(\"...\")] to disambiguate",
        category: "Design",
        defaultSeverity: DiagnosticSeverity.Error,
        isEnabledByDefault: true);

    private static readonly DiagnosticDescriptor DuplicateCaseTypeDescriptor = new(
        id: "UNION009",
        title: "Implicit conversions omitted",
        messageFormat: "Union '{0}' has case types {1} that share one CLR type, so implicit "
                     + "conversions were not generated for them; construct those case wrappers directly",
        category: "Design",
        defaultSeverity: DiagnosticSeverity.Warning,
        isEnabledByDefault: true);

    private static readonly DiagnosticDescriptor GenericRootNameShadowingDescriptor = new(
        id: "UNION010",
        title: "Generic union root needs distinct case names",
        messageFormat: "Union '{0}' is generic, so case '{1}' needs an explicit wrapper name; "
                     + "add [UnionCaseName<{1}>(\"{1}Case\")] because a nested type named '{1}' "
                     + "would shadow the case type in the attribute's own scope",
        category: "Design",
        defaultSeverity: DiagnosticSeverity.Warning,
        isEnabledByDefault: true);

    /// <summary>
    /// Like <see cref="SymbolDisplayFormat.FullyQualifiedFormat"/>, but without
    /// <see cref="SymbolDisplayMiscellaneousOptions.UseSpecialTypes"/>: generated code needs the
    /// CLR name for special types too, e.g. <c>global::System.Int32</c> rather than <c>int</c>,
    /// so it lines up with the wrapper names <see cref="UnionCaseNaming"/> derives from them.
    /// </summary>
    private static readonly SymbolDisplayFormat FullyQualifiedNoKeywordsFormat = new(
        globalNamespaceStyle: SymbolDisplayGlobalNamespaceStyle.Included,
        typeQualificationStyle: SymbolDisplayTypeQualificationStyle.NameAndContainingTypesAndNamespaces,
        genericsOptions: SymbolDisplayGenericsOptions.IncludeTypeParameters,
        miscellaneousOptions: SymbolDisplayMiscellaneousOptions.EscapeKeywordIdentifiers);

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        // Debug support
#if DEBUG
        if (!System.Diagnostics.Debugger.IsAttached)
        {
            // System.Diagnostics.Debugger.Launch();
        }
#endif

        // Test basic generation
        context.RegisterPostInitializationOutput(static ctx =>
        {
            ctx.AddSource("UnionGeneratorTest.g.cs", @"// <auto-generated/>
// Union Generator is active and working
namespace Corsinvest.Fx.Functional
{
    public static class UnionGeneratorTest
    {
        public const bool IsActive = true;
    }
}");
        });

        // Find types with [Union] attribute
        var unionDeclarations = context.SyntaxProvider
            .CreateSyntaxProvider(
                predicate: static (node, _) => IsUnionCandidate(node),
                transform: static (ctx, _) => GetUnionGenerationContext(ctx))
            .Where(static ctx => ctx is not null);

        context.RegisterSourceOutput(
            unionDeclarations,
            static (spc, genContext) => ProcessUnionGeneration(spc, genContext!));

        // Generic attribute path: [Union<T1, ..., Tn>] on a root with no nested cases.
        // ForAttributeWithMetadataName needs a compile-time constant metadata name, which bakes in
        // the arity, so each arity from 1 to 8 needs its own registration.
        RegisterGenericUnionProvider(context, "Corsinvest.Fx.Functional.UnionAttribute`1");
        RegisterGenericUnionProvider(context, "Corsinvest.Fx.Functional.UnionAttribute`2");
        RegisterGenericUnionProvider(context, "Corsinvest.Fx.Functional.UnionAttribute`3");
        RegisterGenericUnionProvider(context, "Corsinvest.Fx.Functional.UnionAttribute`4");
        RegisterGenericUnionProvider(context, "Corsinvest.Fx.Functional.UnionAttribute`5");
        RegisterGenericUnionProvider(context, "Corsinvest.Fx.Functional.UnionAttribute`6");
        RegisterGenericUnionProvider(context, "Corsinvest.Fx.Functional.UnionAttribute`7");
        RegisterGenericUnionProvider(context, "Corsinvest.Fx.Functional.UnionAttribute`8");
    }

    /// <summary>
    /// Wires up the generic <c>[Union&lt;...&gt;]</c> pipeline for one attribute arity.
    /// </summary>
    /// <param name="context">The generator initialization context to register against.</param>
    /// <param name="attributeMetadataName">
    /// The fully-qualified metadata name of the arity-specific attribute, e.g.
    /// <c>Corsinvest.Fx.Functional.UnionAttribute`2</c>.
    /// </param>
    private static void RegisterGenericUnionProvider(IncrementalGeneratorInitializationContext context,
                                                      string attributeMetadataName)
    {
        var genericUnions = context.SyntaxProvider
            .ForAttributeWithMetadataName(
                attributeMetadataName,
                predicate: static (node, _) => node is RecordDeclarationSyntax,
                transform: static (ctx, _) => BuildGenericUnionInfo(ctx))
            .Where(static info => info is not null);

        context.RegisterSourceOutput(
            genericUnions,
            static (spc, info) => GenerateGenericUnion(spc, info!));
    }

    private static bool IsUnionCandidate(SyntaxNode node)
        => node is RecordDeclarationSyntax record
            && record.AttributeLists.Count > 0;

    private static UnionGenerationContext? GetUnionGenerationContext(GeneratorSyntaxContext context)
    {
        var record = (RecordDeclarationSyntax)context.Node;
        var diagnostics = new List<Diagnostic>();

        // Resolve the attribute through the semantic model: a textual name match would also
        // fire on unrelated attributes that merely contain "Union" (e.g. [MyUnionHelper]).
        var hasUnionAttribute = record.AttributeLists
                                      .SelectMany(al => al.Attributes)
                                      .Any(a => IsUnionAttribute(a, context.SemanticModel));
        if (!hasUnionAttribute)
        {
            return null;
        }

        // Check if main record is partial
        var isPartial = record.Modifiers.Any(m => m.IsKind(SyntaxKind.PartialKeyword));
        if (!isPartial)
        {
            var diagnostic = Diagnostic.Create(
                UnionMustBePartialDescriptor,
                record.Identifier.GetLocation(),
                record.Identifier.Text);
            diagnostics.Add(diagnostic);

            // Return context with diagnostics only, no code generation
            return new UnionGenerationContext(null, diagnostics);
        }

        // Get all nested records (variants)
        var allVariants = record.Members.OfType<RecordDeclarationSyntax>().ToList();
        var variants = new List<VariantInfo>();

        foreach (var variant in allVariants)
        {
            var isVariantPartial = variant.Modifiers.Any(m => m.IsKind(SyntaxKind.PartialKeyword));

            if (!isVariantPartial)
            {
                // Report diagnostic for non-partial variant
                var diagnostic = Diagnostic.Create(
                    VariantMustBePartialDescriptor,
                    variant.Identifier.GetLocation(),
                    variant.Identifier.Text,
                    record.Identifier.Text);
                diagnostics.Add(diagnostic);
            }
            else
            {
                // Add to variants list only if partial
                variants.Add(new VariantInfo(
                    Name: variant.Identifier.Text,
                    Parameters: variant.ParameterList?.Parameters
                        .Select(p => new ParamInfo(p.Type!.ToString(), p.Identifier.Text))
                        .ToList() ?? []
                ));
            }
        }

        var unionInfo = new UnionInfo(
            Namespace: GetNamespace(record),
            TypeName: record.Identifier.Text,
            TypeParameters: GetTypeParameters(record),
            Variants: variants,
            Location: record.Identifier.GetLocation()
        );

        return new UnionGenerationContext(unionInfo, diagnostics);
    }

    private const string UnionAttributeMetadataName = "Corsinvest.Fx.Functional.UnionAttribute";

    private static bool IsUnionAttribute(AttributeSyntax attribute, SemanticModel semanticModel)
    {
        var symbol = semanticModel.GetSymbolInfo(attribute).Symbol
                     ?? semanticModel.GetSymbolInfo(attribute).CandidateSymbols.FirstOrDefault();

        var attributeType = (symbol as IMethodSymbol)?.ContainingType ?? symbol as INamedTypeSymbol;

        return attributeType?.ToDisplayString() == UnionAttributeMetadataName;
    }

    private static string GetNamespace(SyntaxNode node)
    {
        var parent = node.Parent;
        while (parent != null)
        {
            if (parent is NamespaceDeclarationSyntax ns) { return ns.Name.ToString(); }
            if (parent is FileScopedNamespaceDeclarationSyntax fsns) { return fsns.Name.ToString(); }

            parent = parent.Parent;
        }
        return string.Empty;
    }

    private static string GetTypeParameters(RecordDeclarationSyntax record)
        => record.TypeParameterList is null
            ? string.Empty
            : record.TypeParameterList.ToString();

    private static void ProcessUnionGeneration(SourceProductionContext context, UnionGenerationContext genContext)
    {
        // Report all diagnostics first
        foreach (var diagnostic in genContext.Diagnostics)
        {
            context.ReportDiagnostic(diagnostic);
        }

        // Only generate code if UnionInfo is available (no critical errors)
        if (genContext.UnionInfo is not null)
        {
            GenerateUnion(context, genContext.UnionInfo);
        }
    }

    private static void GenerateUnion(SourceProductionContext context, UnionInfo unionInfo)
    {
        try
        {
            context.AddSource($"{unionInfo.TypeName}.g.cs", GenerateUnionSource(unionInfo));
        }
        catch (Exception ex)
        {
            // Report diagnostic for generation errors
            context.ReportDiagnostic(Diagnostic.Create(
                UnionGenerationFailedDescriptor,
                unionInfo.Location ?? Location.None,
                unionInfo.TypeName,
                ex.Message));
        }
    }

    private static string GenerateUnionSource(UnionInfo unionInfo)
    {
        var sb = new StringBuilder();

        // Header
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Threading.Tasks;");
        sb.AppendLine();

        if (!string.IsNullOrEmpty(unionInfo.Namespace))
        {
            sb.AppendLine($"namespace {unionInfo.Namespace};");
            sb.AppendLine();
        }

        // Type declaration
        sb.AppendLine($"public partial record {unionInfo.TypeName}{unionInfo.TypeParameters}");
        sb.AppendLine("{");

        // Private constructor (sealed hierarchy)
        sb.AppendLine($"    private {unionInfo.TypeName}() {{ }}");
        sb.AppendLine();

        // Sealed variants
        foreach (var variant in unionInfo.Variants)
        {
            GenerateVariant(sb, unionInfo, variant);
        }

        // Type checking properties
        foreach (var variant in unionInfo.Variants)
        {
            sb.AppendLine($"    public bool Is{variant.Name} => this is {variant.Name};");
        }
        sb.AppendLine();

        // Match methods
        GenerateMatchMethods(sb, unionInfo);

        // TryGet methods
        GenerateTryGetMethods(sb, unionInfo);

        sb.AppendLine("}");

        // Union extensions 
        GenerateUnionExtensions(sb, unionInfo);

        return sb.ToString();
    }

    private static void GenerateVariant(StringBuilder sb, UnionInfo unionInfo, VariantInfo variant)
    {
        // For records without parameters, generate a simple sealed record
        // For records with parameters, the parameters are already in the user declaration
        sb.AppendLine($"    public sealed partial record {variant.Name} : {unionInfo.TypeName}{unionInfo.TypeParameters};");
        sb.AppendLine();
    }

    private static void GenerateUnionExtensions(StringBuilder sb, UnionInfo unionInfo)
    {
        // Parametri generici della union
        var genericParamsList = !string.IsNullOrEmpty(unionInfo.TypeParameters)
            ? unionInfo.TypeParameters.Trim('<', '>').Split(',').Select(p => p.Trim()).ToList()
            : [];

        // Classe di estensione
        sb.AppendLine($"public static class {unionInfo.TypeName}UnionExtensions");
        sb.AppendLine("{");

        // 1️⃣ Async Match con TResult (Task<TResult>) -> Func<Task<TResult>>
        {
            var methodGenericParams = new List<string>(genericParamsList) { "TResult" };
            var methodGenericParamsString = $"<{string.Join(", ", methodGenericParams)}>";

            sb.AppendLine($"    public static async Task<TResult> MatchAsync{methodGenericParamsString}(");
            sb.AppendLine($"        this Task<{unionInfo.TypeName}{unionInfo.TypeParameters}> task,");

            for (int i = 0; i < unionInfo.Variants.Count; i++)
            {
                var variant = unionInfo.Variants[i];
                var comma = i < unionInfo.Variants.Count - 1 ? "," : string.Empty;
                sb.AppendLine($"        Func<{unionInfo.TypeName}{unionInfo.TypeParameters}.{variant.Name}, Task<TResult>> on{variant.Name}{comma}");
            }

            sb.AppendLine("    )");
            sb.AppendLine("    {");
            sb.AppendLine("        var result = await task;");
            sb.AppendLine("        return await result.MatchAsync(");
            for (int i = 0; i < unionInfo.Variants.Count; i++)
            {
                var variant = unionInfo.Variants[i];
                var comma = i < unionInfo.Variants.Count - 1 ? "," : string.Empty;
                sb.AppendLine($"            on{variant.Name}{comma}");
            }
            sb.AppendLine("        );");
            sb.AppendLine("    }");
            sb.AppendLine();
        }

        // 2️⃣ Async Match senza TResult (Task) -> Func<Task>
        {
            var methodGenericParamsString = genericParamsList.Count > 0 
                                                ? $"<{string.Join(", ", genericParamsList)}>" 
                                                : string.Empty;

            sb.AppendLine($"    public static async Task MatchAsync{methodGenericParamsString}(");
            sb.AppendLine($"        this Task<{unionInfo.TypeName}{unionInfo.TypeParameters}> task,");

            for (int i = 0; i < unionInfo.Variants.Count; i++)
            {
                var variant = unionInfo.Variants[i];
                var comma = i < unionInfo.Variants.Count - 1 
                                ? "," 
                                : string.Empty;

                sb.AppendLine($"        Func<{unionInfo.TypeName}{unionInfo.TypeParameters}.{variant.Name}, Task> on{variant.Name}{comma}");
            }

            sb.AppendLine("    )");
            sb.AppendLine("    {");
            sb.AppendLine("        var result = await task;");
            sb.AppendLine("        await result.MatchAsync(");
            for (int i = 0; i < unionInfo.Variants.Count; i++)
            {
                var variant = unionInfo.Variants[i];
                var comma = i < unionInfo.Variants.Count - 1 
                            ? "," 
                            : string.Empty;

                sb.AppendLine($"            on{variant.Name}{comma}");
            }
            sb.AppendLine("        );");
            sb.AppendLine("    }");
            sb.AppendLine();
        }

        // 3️⃣ Async Match con TResult (Task<TResult>) -> Func<TResult> (sincrona)
        {
            var methodGenericParams = new List<string>(genericParamsList) { "TResult" };
            var methodGenericParamsString = $"<{string.Join(", ", methodGenericParams)}>";

            sb.AppendLine($"    public static async Task<TResult> MatchAsync{methodGenericParamsString}(");
            sb.AppendLine($"        this Task<{unionInfo.TypeName}{unionInfo.TypeParameters}> task,");
            for (int i = 0; i < unionInfo.Variants.Count; i++)
            {
                var variant = unionInfo.Variants[i];
                var comma = i < unionInfo.Variants.Count - 1 
                                ? "," 
                                : string.Empty;

                sb.AppendLine($"        Func<{unionInfo.TypeName}{unionInfo.TypeParameters}.{variant.Name}, TResult> on{variant.Name}{comma}");
            }

            sb.AppendLine("    )");
            sb.AppendLine("    {");
            sb.AppendLine("        var result = await task;");
            sb.AppendLine("        return result.Match(");
            for (int i = 0; i < unionInfo.Variants.Count; i++)
            {
                var variant = unionInfo.Variants[i];
                var comma = i < unionInfo.Variants.Count - 1 
                                ? "," 
                                : string.Empty;

                sb.AppendLine($"            on{variant.Name}{comma}");
            }
            sb.AppendLine("        );");
            sb.AppendLine("    }");

        }

        sb.AppendLine("}");
    }

    private static void GenerateMatchMethods(StringBuilder sb, UnionInfo unionInfo)
    {
        // Sync Match with return value
        sb.AppendLine("    public TResult Match<TResult>(");
        for (int i = 0; i < unionInfo.Variants.Count; i++)
        {
            var variant = unionInfo.Variants[i];
            var comma = i < unionInfo.Variants.Count - 1 
                            ? "," 
                            : string.Empty;

            sb.AppendLine($"        Func<{variant.Name}, TResult> on{variant.Name}{comma}");
        }
        sb.AppendLine("    )");
        sb.AppendLine("    {");
        sb.AppendLine("        return this switch");
        sb.AppendLine("        {");
        foreach (var variant in unionInfo.Variants)
        {
            sb.AppendLine($"            {variant.Name} {variant.Name.ToLowerInvariant()} => on{variant.Name}({variant.Name.ToLowerInvariant()}),");
        }
        sb.AppendLine("            _ => throw new InvalidOperationException(\"Invalid union state\")");
        sb.AppendLine("        };");
        sb.AppendLine("    }");
        sb.AppendLine();

        // Sync Match without return value
        sb.AppendLine("    public void Match(");
        for (int i = 0; i < unionInfo.Variants.Count; i++)
        {
            var variant = unionInfo.Variants[i];
            var comma = i < unionInfo.Variants.Count - 1 
                            ? "," 
                            : string.Empty;

            sb.AppendLine($"        Action<{variant.Name}> on{variant.Name}{comma}");
        }
        sb.AppendLine("    )");
        sb.AppendLine("    {");
        sb.AppendLine("        switch (this)");
        sb.AppendLine("        {");
        foreach (var variant in unionInfo.Variants)
        {
            sb.AppendLine($"            case {variant.Name} {variant.Name.ToLowerInvariant()}:");
            sb.AppendLine($"                on{variant.Name}({variant.Name.ToLowerInvariant()});");
            sb.AppendLine("                break;");
        }
        sb.AppendLine("            default:");
        sb.AppendLine("                throw new InvalidOperationException(\"Invalid union state\");");
        sb.AppendLine("        }");
        sb.AppendLine("    }");
        sb.AppendLine();

        // Async Match methods
        GenerateAsyncMatchMethods(sb, unionInfo);
    }

    private static void GenerateAsyncMatchMethods(StringBuilder sb, UnionInfo unionInfo)
    {
        // Async Match with return value
        sb.AppendLine("    public async Task<TResult> MatchAsync<TResult>(");
        for (int i = 0; i < unionInfo.Variants.Count; i++)
        {
            var variant = unionInfo.Variants[i];
            var comma = i < unionInfo.Variants.Count - 1 
                            ? "," 
                            : string.Empty;

            sb.AppendLine($"        Func<{variant.Name}, Task<TResult>> on{variant.Name}{comma}");
        }
        sb.AppendLine("    )");
        sb.AppendLine("    {");
        sb.AppendLine("        return this switch");
        sb.AppendLine("        {");
        foreach (var variant in unionInfo.Variants)
        {
            sb.AppendLine($"            {variant.Name} {variant.Name.ToLowerInvariant()} => await on{variant.Name}({variant.Name.ToLowerInvariant()}),");
        }
        sb.AppendLine("            _ => throw new InvalidOperationException(\"Invalid union state\")");
        sb.AppendLine("        };");
        sb.AppendLine("    }");
        sb.AppendLine();

        // Async Match without return value
        sb.AppendLine("    public async Task MatchAsync(");
        for (int i = 0; i < unionInfo.Variants.Count; i++)
        {
            var variant = unionInfo.Variants[i];
            var comma = i < unionInfo.Variants.Count - 1 
                        ? "," 
                        : string.Empty;

            sb.AppendLine($"        Func<{variant.Name}, Task> on{variant.Name}{comma}");
        }
        sb.AppendLine("    )");
        sb.AppendLine("    {");
        sb.AppendLine("        switch (this)");
        sb.AppendLine("        {");
        foreach (var variant in unionInfo.Variants)
        {
            sb.AppendLine($"            case {variant.Name} {variant.Name.ToLowerInvariant()}:");
            sb.AppendLine($"                await on{variant.Name}({variant.Name.ToLowerInvariant()});");
            sb.AppendLine("                break;");
        }
        sb.AppendLine("            default:");
        sb.AppendLine("                throw new InvalidOperationException(\"Invalid union state\");");
        sb.AppendLine("        }");
        sb.AppendLine("    }");
        sb.AppendLine();
    }

    private static void GenerateTryGetMethods(StringBuilder sb, UnionInfo unionInfo)
    {
        foreach (var variant in unionInfo.Variants)
        {
            sb.AppendLine($"    public bool TryGet{variant.Name}(out {variant.Name} {variant.Name.ToLowerInvariant()})");
            sb.AppendLine("    {");
            sb.AppendLine($"        if (this is {variant.Name} {variant.Name.ToLowerInvariant()}Value)");
            sb.AppendLine("        {");
            sb.AppendLine($"            {variant.Name.ToLowerInvariant()} = {variant.Name.ToLowerInvariant()}Value;");
            sb.AppendLine("            return true;");
            sb.AppendLine("        }");
            sb.AppendLine($"        {variant.Name.ToLowerInvariant()} = default!;");
            sb.AppendLine("        return false;");
            sb.AppendLine("    }");
            sb.AppendLine();
        }
    }

    // ---- Generic [Union<T1..T8>] path --------------------------------------

    /// <summary>
    /// Builds the model for one <c>[Union&lt;...&gt;]</c> declaration from the generator's
    /// attribute-target context, or null when the target does not describe a usable union.
    /// </summary>
    /// <param name="context">The attribute target context supplied by <c>ForAttributeWithMetadataName</c>.</param>
    private static GenericUnionInfo? BuildGenericUnionInfo(GeneratorAttributeSyntaxContext context)
    {
        if (context.TargetSymbol is not INamedTypeSymbol root) { return null; }

        var attribute = context.Attributes[0];
        if (attribute.AttributeClass is not { } attributeClass) { return null; }

        var caseTypes = attributeClass.TypeArguments;
        if (caseTypes.Length == 0) { return null; }

        var overrides = ReadCaseNameOverrides(root);
        var names = UnionCaseNaming.ResolveNames(caseTypes, overrides, out var hasNameCollision);

        // Duplicate CLR types make duplicate conversion operators illegal (CS0557). Named tuples
        // with different element names, e.g. (int X, int Y) and (int Row, int Col), are distinct
        // to SymbolEqualityComparer but erase to the same metadata type ValueTuple<int, int>, so
        // compare by a canonical form with tuple element names stripped at every nesting level
        // (GetCanonicalClrType) instead of the case type symbol itself.
        var distinctClrTypes = caseTypes
            .Select(GetCanonicalClrType)
            .Distinct(SymbolEqualityComparer.Default)
            .Count();

        return new GenericUnionInfo(
            @namespace: root.ContainingNamespace.IsGlobalNamespace
                ? string.Empty
                : root.ContainingNamespace.ToDisplayString(),
            typeName: root.Name,
            typeParameters: root.TypeParameters.Length == 0
                ? string.Empty
                : "<" + string.Join(", ", root.TypeParameters.Select(p => p.Name)) + ">",
            caseTypes: caseTypes,
            caseNames: names,
            emitImplicitConversions: distinctClrTypes == caseTypes.Length,
            hasNameCollision: hasNameCollision,
            location: root.Locations.FirstOrDefault());
    }

    /// <summary>
    /// Reduces a type to the form the CLR actually sees, so that two case types compare equal
    /// exactly when they would produce colliding metadata signatures. Tuple element names are a
    /// source-only, compiler-synthesized annotation (via <see cref="System.Runtime.CompilerServices.TupleElementNamesAttribute"/>)
    /// that <see cref="SymbolEqualityComparer"/> still distinguishes; stripping only the
    /// outermost tuple's names (via <see cref="INamedTypeSymbol.TupleUnderlyingType"/>) is not
    /// enough, because a tuple nested inside another tuple's type arguments — or inside any other
    /// generic type's type arguments — keeps its own element names even after the outer
    /// substitution. This recurses through every generic type argument so nested tuples are
    /// stripped at every level, e.g. both <c>(int X, (int A, int B) Y)</c> and
    /// <c>(int Row, (int C, int D) Col)</c> canonicalize to the same
    /// <c>ValueTuple&lt;int, ValueTuple&lt;int, int&gt;&gt;</c>. Non-tuple, non-generic types
    /// (and generic types with no tuple anywhere in their arguments) are returned unchanged, so
    /// this can never make two genuinely different CLR types compare equal - only ever collapses
    /// distinctions that tuple element names introduce.
    /// </summary>
    /// <param name="type">The type to canonicalize.</param>
    private static ITypeSymbol GetCanonicalClrType(ITypeSymbol type)
    {
        if (type is not INamedTypeSymbol named) { return type; }

        // A tuple's TupleUnderlyingType is itself IsTupleType == true in Roslyn (the unnamed
        // ValueTuple<...> instantiation is still "a tuple type", just without friendly element
        // names) - recursing back through GetCanonicalClrType on it would recurse forever. Strip
        // the name layer at most once per level, then fall through to the general generic-type
        // branch below to canonicalize its type arguments (which is what actually reaches any
        // nested tuple).
        var underlying = named.IsTupleType ? named.TupleUnderlyingType ?? named : named;

        if (underlying.IsGenericType && underlying.TypeArguments.Length > 0)
        {
            var canonicalArguments = underlying.TypeArguments
                .Select(GetCanonicalClrType)
                .ToArray();

            // Reconstructing with unchanged arguments returns an equivalent symbol, so it is safe
            // to always go through Construct rather than special-casing "nothing changed".
            return underlying.ConstructedFrom.Construct(canonicalArguments);
        }

        return underlying;
    }

    /// <summary>
    /// Finds the wrapper (case) names whose case types canonicalize to a CLR type shared with at
    /// least one other case, in declaration order, for UNION009's message.
    /// </summary>
    /// <param name="info">The resolved union model to inspect.</param>
    private static IEnumerable<string> GetCasesSharingAClrType(GenericUnionInfo info)
    {
        var canonical = info.CaseTypes.Select(GetCanonicalClrType).ToArray();

        var duplicatedClrTypes = canonical
            .GroupBy(t => t, SymbolEqualityComparer.Default)
            .Where(g => g.Count() > 1)
            .Select(g => g.Key)
            .ToImmutableHashSet(SymbolEqualityComparer.Default);

        for (var i = 0; i < canonical.Length; i++)
        {
            if (duplicatedClrTypes.Contains(canonical[i]))
            {
                yield return info.CaseNames[i];
            }
        }
    }

    /// <summary>
    /// Reads the <c>[UnionCaseName&lt;T&gt;("...")]</c> overrides declared on a union root.
    /// </summary>
    /// <param name="root">The union root type to inspect.</param>
    private static IReadOnlyDictionary<ITypeSymbol, string> ReadCaseNameOverrides(INamedTypeSymbol root)
    {
        var overrides = new Dictionary<ITypeSymbol, string>(SymbolEqualityComparer.Default);

        foreach (var attribute in root.GetAttributes())
        {
            if (attribute.AttributeClass is not { Name: "UnionCaseNameAttribute" } attributeClass) { continue; }
            if (attributeClass.TypeArguments.Length != 1) { continue; }
            if (attribute.ConstructorArguments.Length != 1) { continue; }
            if (attribute.ConstructorArguments[0].Value is not string name) { continue; }

            overrides[attributeClass.TypeArguments[0]] = name;
        }

        return overrides;
    }

    /// <summary>
    /// Emits the generated source for one generic <c>[Union&lt;...&gt;]</c> declaration.
    /// </summary>
    /// <param name="context">The source production context to add the generated file to.</param>
    /// <param name="info">The resolved union model built by <see cref="BuildGenericUnionInfo"/>.</param>
    private static void GenerateGenericUnion(SourceProductionContext context, GenericUnionInfo info)
    {
        if (info.HasNameCollision)
        {
            context.ReportDiagnostic(Diagnostic.Create(
                CaseNameCollisionDescriptor, info.Location ?? Location.None, info.TypeName));
            return;
        }

        if (!info.EmitImplicitConversions)
        {
            var collidingCaseNames = string.Join(", ", GetCasesSharingAClrType(info));

            context.ReportDiagnostic(Diagnostic.Create(
                DuplicateCaseTypeDescriptor, info.Location ?? Location.None, info.TypeName, collidingCaseNames));
        }

        // A generic root's nested wrapper shares the attribute's own scope: if a wrapper name
        // equals its case type's simple name, the merged partial declaration shadows the
        // top-level case type for the attribute's own type-argument lookup, and the compiler
        // rejects it with CS8968. Warn and name the fix (UnionCaseName<T>) rather than leaving
        // the user with a bare, unexplained compiler error.
        if (info.TypeParameters.Length > 0)
        {
            for (var i = 0; i < info.CaseTypes.Length; i++)
            {
                if (info.CaseNames[i] == info.CaseTypes[i].Name)
                {
                    context.ReportDiagnostic(Diagnostic.Create(
                        GenericRootNameShadowingDescriptor,
                        info.Location ?? Location.None,
                        info.TypeName,
                        info.CaseNames[i]));
                }
            }
        }

        var sb = new StringBuilder();

        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Threading.Tasks;");
        sb.AppendLine();

        if (!string.IsNullOrEmpty(info.Namespace))
        {
            sb.AppendLine($"namespace {info.Namespace};");
            sb.AppendLine();
        }

        var root = info.TypeName + info.TypeParameters;

        sb.AppendLine($"public abstract partial record {root}");
        sb.AppendLine("{");
        sb.AppendLine($"    private {info.TypeName}() {{ }}");
        sb.AppendLine();

        var qualified = info.CaseTypes
            .Select(t => t.ToDisplayString(FullyQualifiedNoKeywordsFormat))
            .ToImmutableArray();

        // Wrappers
        for (var i = 0; i < info.CaseNames.Length; i++)
        {
            sb.AppendLine($"    public sealed partial record {info.CaseNames[i]}({qualified[i]} Value) : {root};");
        }
        sb.AppendLine();

        // Implicit conversions
        if (info.EmitImplicitConversions)
        {
            for (var i = 0; i < info.CaseNames.Length; i++)
            {
                sb.AppendLine($"    public static implicit operator {root}({qualified[i]} value) => new {info.CaseNames[i]}(value);");
            }
            sb.AppendLine();
        }

        // Is* properties
        foreach (var name in info.CaseNames)
        {
            sb.AppendLine($"    public bool Is{name} => this is {name};");
        }
        sb.AppendLine();

        GenerateGenericMatch(sb, info, qualified, root);
        GenerateGenericTryGet(sb, info, qualified);

        sb.AppendLine("}");

        context.AddSource($"{info.TypeName}.Union.g.cs", sb.ToString());
    }

    /// <summary>
    /// Appends the synchronous, void, and async <c>Match</c> overloads for a generic union.
    /// </summary>
    /// <param name="sb">The source builder to append to.</param>
    /// <param name="info">The union model supplying case names.</param>
    /// <param name="qualified">Fully-qualified case type names, aligned with <paramref name="info"/>'s case names.</param>
    /// <param name="root">The union root type name including type parameters.</param>
    private static void GenerateGenericMatch(StringBuilder sb,
                                             GenericUnionInfo info,
                                             ImmutableArray<string> qualified,
                                             string root)
    {
        // Match with a result
        sb.AppendLine("    public TResult Match<TResult>(");
        for (var i = 0; i < info.CaseNames.Length; i++)
        {
            var comma = i < info.CaseNames.Length - 1 ? "," : string.Empty;
            sb.AppendLine($"        Func<{qualified[i]}, TResult> on{info.CaseNames[i]}{comma}");
        }
        sb.AppendLine("    )");
        sb.AppendLine("        => this switch");
        sb.AppendLine("        {");
        foreach (var name in info.CaseNames)
        {
            sb.AppendLine($"            {name} wrapped => on{name}(wrapped.Value),");
        }
        sb.AppendLine("            _ => throw new InvalidOperationException(\"Invalid union state\")");
        sb.AppendLine("        };");
        sb.AppendLine();

        // Match without a result
        sb.AppendLine("    public void Match(");
        for (var i = 0; i < info.CaseNames.Length; i++)
        {
            var comma = i < info.CaseNames.Length - 1 ? "," : string.Empty;
            sb.AppendLine($"        Action<{qualified[i]}> on{info.CaseNames[i]}{comma}");
        }
        sb.AppendLine("    )");
        sb.AppendLine("    {");
        sb.AppendLine("        switch (this)");
        sb.AppendLine("        {");
        foreach (var name in info.CaseNames)
        {
            sb.AppendLine($"            case {name} wrapped: on{name}(wrapped.Value); break;");
        }
        sb.AppendLine("            default: throw new InvalidOperationException(\"Invalid union state\");");
        sb.AppendLine("        }");
        sb.AppendLine("    }");
        sb.AppendLine();

        // Async match
        sb.AppendLine("    public async Task<TResult> MatchAsync<TResult>(");
        for (var i = 0; i < info.CaseNames.Length; i++)
        {
            var comma = i < info.CaseNames.Length - 1 ? "," : string.Empty;
            sb.AppendLine($"        Func<{qualified[i]}, Task<TResult>> on{info.CaseNames[i]}{comma}");
        }
        sb.AppendLine("    )");
        sb.AppendLine("        => this switch");
        sb.AppendLine("        {");
        foreach (var name in info.CaseNames)
        {
            sb.AppendLine($"            {name} wrapped => await on{name}(wrapped.Value),");
        }
        sb.AppendLine("            _ => throw new InvalidOperationException(\"Invalid union state\")");
        sb.AppendLine("        };");
        sb.AppendLine();
    }

    /// <summary>
    /// Appends one <c>TryGetX</c> method per case type for a generic union.
    /// </summary>
    /// <param name="sb">The source builder to append to.</param>
    /// <param name="info">The union model supplying case names.</param>
    /// <param name="qualified">Fully-qualified case type names, aligned with <paramref name="info"/>'s case names.</param>
    private static void GenerateGenericTryGet(StringBuilder sb,
                                              GenericUnionInfo info,
                                              ImmutableArray<string> qualified)
    {
        for (var i = 0; i < info.CaseNames.Length; i++)
        {
            var name = info.CaseNames[i];
            sb.AppendLine($"    public bool TryGet{name}(out {qualified[i]} value)");
            sb.AppendLine("    {");
            sb.AppendLine($"        if (this is {name} wrapped) {{ value = wrapped.Value; return true; }}");
            sb.AppendLine("        value = default!;");
            sb.AppendLine("        return false;");
            sb.AppendLine("    }");
            sb.AppendLine();
        }
    }

}

// Data structures for union metadata
internal record UnionInfo(
    string Namespace,
    string TypeName,
    string TypeParameters,
    List<VariantInfo> Variants,
    Location? Location
);

internal record VariantInfo(string Name, List<ParamInfo> Parameters);
internal record ParamInfo(string Type, string Name);

internal record UnionGenerationContext(
    UnionInfo? UnionInfo,
    List<Diagnostic> Diagnostics
);