using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using System.Collections.Immutable;
using System.Text;

namespace Corsinvest.Fx.Functional;

[Generator]
public class UnionGenerator : IIncrementalGenerator
{
    // Diagnostic descriptors
    private static readonly DiagnosticDescriptor UnionGenerationFailedDescriptor = new(
        id: "UNION001",
        title: "Union generation failed",
        messageFormat: "Failed to generate union for '{0}': {1}",
        category: "Generator",
        defaultSeverity: DiagnosticSeverity.Error,
        isEnabledByDefault: true);

    private static readonly DiagnosticDescriptor CaseNameCollisionDescriptor = new(
        id: "UNION008",
        title: "Union case names collide",
        messageFormat: "Union '{0}' has case types that resolve to the same wrapper name; "
                     + "use [UnionCaseName<T>(\"...\")] to disambiguate",
        category: "Design",
        defaultSeverity: DiagnosticSeverity.Error,
        isEnabledByDefault: true);

    private static readonly DiagnosticDescriptor DuplicateCaseTypeDescriptor = new(
        id: "UNION009",
        title: "Implicit conversions omitted",
        messageFormat: "Union '{0}' has case types {1} that share one CLR type, so implicit "
                     + "conversions were not generated for them; construct those case wrappers directly",
        category: "Design",
        defaultSeverity: DiagnosticSeverity.Warning,
        isEnabledByDefault: true);

    private static readonly DiagnosticDescriptor InterfaceCaseTypeDescriptor = new(
        id: "UNION012",
        title: "Union case type cannot be an interface",
        messageFormat: "Union '{0}' has case type '{1}', which is an interface; C# forbids a "
                     + "user-defined conversion to or from an interface, so the generated implicit "
                     + "conversion cannot compile",
        category: "Design",
        defaultSeverity: DiagnosticSeverity.Error,
        isEnabledByDefault: true);

    /// <summary>
    /// Like <see cref="SymbolDisplayFormat.FullyQualifiedFormat"/>, but without
    /// <see cref="SymbolDisplayMiscellaneousOptions.UseSpecialTypes"/>: generated code needs the
    /// CLR name for special types too, e.g. <c>global::System.Int32</c> rather than <c>int</c>,
    /// so it lines up with the wrapper names <see cref="UnionCaseNaming"/> derives from them.
    /// </summary>
    private static readonly SymbolDisplayFormat FullyQualifiedNoKeywordsFormat = new(
        globalNamespaceStyle: SymbolDisplayGlobalNamespaceStyle.Included,
        typeQualificationStyle: SymbolDisplayTypeQualificationStyle.NameAndContainingTypesAndNamespaces,
        genericsOptions: SymbolDisplayGenericsOptions.IncludeTypeParameters,
        miscellaneousOptions: SymbolDisplayMiscellaneousOptions.EscapeKeywordIdentifiers);

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        // Debug support
#if DEBUG
        if (!System.Diagnostics.Debugger.IsAttached)
        {
            // System.Diagnostics.Debugger.Launch();
        }
#endif

        // Test basic generation
        context.RegisterPostInitializationOutput(static ctx =>
        {
            ctx.AddSource("UnionGeneratorTest.g.cs", @"// <auto-generated/>
// Union Generator is active and working
namespace Corsinvest.Fx.Functional
{
    public static class UnionGeneratorTest
    {
        public const bool IsActive = true;
    }
}");
        });

        // Find union roots: a partial record that implements IUnion<...>. Roslyn substitutes the
        // root's own type parameters into the interface's type arguments before we ever see them,
        // so there is no substitution logic here - marker.TypeArguments already hands us the case
        // types with the root's <T> baked in.
        var unionRoots = context.SyntaxProvider
            .CreateSyntaxProvider(
                predicate: static (node, _) => node is RecordDeclarationSyntax { BaseList: not null },
                transform: static (ctx, ct) => BuildUnionInfo(ctx, ct))
            .Where(static info => info is not null)
            .Collect()
            .SelectMany(static (infos, _) => DeduplicatePartialDeclarations(infos!));

        context.RegisterSourceOutput(unionRoots, static (spc, info) => GenerateUnion(spc, info));
    }

    private const string UnionInterfaceName = "IUnion";
    private const string UnionNamespace = "Corsinvest.Fx.Functional";

    /// <summary>
    /// Builds the model for one union root declaration from its syntax context, or null when the
    /// declared symbol is not a union root (does not implement <c>IUnion&lt;...&gt;</c>).
    /// </summary>
    /// <param name="context">The syntax context supplied by <c>CreateSyntaxProvider</c>.</param>
    /// <param name="cancellationToken">Cancellation token for the generator pipeline.</param>
    private static UnionInfo? BuildUnionInfo(GeneratorSyntaxContext context, CancellationToken cancellationToken)
    {
        if (context.SemanticModel.GetDeclaredSymbol(context.Node, cancellationToken) is not INamedTypeSymbol root)
        {
            return null;
        }

        var marker = root.Interfaces.FirstOrDefault(
            i => i.Name == UnionInterfaceName
                 && i.ContainingNamespace?.ToDisplayString() == UnionNamespace);

        if (marker is null) { return null; }

        // Roslyn has already substituted the root's type parameters into the case types:
        // for Option<T> : IUnion<Some<T>, None> these arrive as Some<T> and None.
        var caseTypes = marker.TypeArguments;
        if (caseTypes.Length == 0) { return null; }

        var overrides = ReadCaseNameOverrides(root);
        var names = UnionCaseNaming.ResolveNames(caseTypes, overrides, root.TypeParameters, out var hasNameCollision);

        // Duplicate CLR types make duplicate conversion operators illegal (CS0557). Named tuples
        // with different element names, e.g. (int X, int Y) and (int Row, int Col), are distinct
        // to SymbolEqualityComparer but erase to the same metadata type ValueTuple<int, int>, so
        // compare by a canonical form with tuple element names stripped at every nesting level
        // (GetCanonicalClrType) instead of the case type symbol itself.
        var distinctClrTypes = caseTypes
            .Select(GetCanonicalClrType)
            .Distinct(SymbolEqualityComparer.Default)
            .Count();

        return new UnionInfo(
            @namespace: root.ContainingNamespace.IsGlobalNamespace
                ? string.Empty
                : root.ContainingNamespace.ToDisplayString(),
            typeName: root.Name,
            typeParameters: root.TypeParameters.Length == 0
                ? string.Empty
                : "<" + string.Join(", ", root.TypeParameters.Select(p => p.Name)) + ">",
            caseTypes: caseTypes,
            caseNames: names,
            emitImplicitConversions: distinctClrTypes == caseTypes.Length,
            hasNameCollision: hasNameCollision,
            containingTypes: GetContainingTypeChain(root),
            location: root.Locations.FirstOrDefault());
    }

    /// <summary>
    /// Deduplicates union roots that were seen more than once because <c>CreateSyntaxProvider</c>
    /// fires once per partial declaration: a root split across several <c>partial record</c>
    /// pieces would otherwise be built (and its generated file emitted) once per piece, colliding
    /// on the same hint name (CS8785). Keyed by the root's fully-qualified name plus arity, which
    /// uniquely identifies a symbol the way <see cref="BuildHintName"/> does for its output file.
    /// </summary>
    /// <param name="infos">Every non-null union model built from every matching partial declaration.</param>
    private static IEnumerable<UnionInfo> DeduplicatePartialDeclarations(ImmutableArray<UnionInfo> infos)
    {
        var seen = new HashSet<string>();

        foreach (var info in infos)
        {
            var arity = info.TypeParameters.Length == 0
                ? 0
                : info.TypeParameters.Count(c => c == ',') + 1;

            var key = string.Join(
                ".",
                new[] { info.Namespace }
                    .Concat(info.ContainingTypes.Select(t => t.Name))
                    .Append($"{info.TypeName}`{arity}"));

            if (seen.Add(key))
            {
                yield return info;
            }
        }
    }

    /// <summary>
    /// Builds a hint name that is unique across the whole compilation for
    /// <see cref="SourceProductionContext.AddSource(string, string)"/>, from the namespace,
    /// containing-type chain, type name and (for a generic root) its arity.
    /// </summary>
    /// <remarks>
    /// The bare type name alone collides whenever two unions share a name in different namespaces
    /// or containing types - ordinary in real code (<c>Billing.Result</c>, <c>Shipping.Result</c>)
    /// - which fails with <c>CS8785</c> and silently drops generation for every union after the
    /// first with that name. Dots are legal in a hint name; angle brackets, commas and other
    /// characters that show up in a type parameter list are not, so anything outside
    /// <c>[A-Za-z0-9_.]</c> is replaced with <c>_</c>.
    /// </remarks>
    /// <param name="namespace">The union root's namespace, or empty for the global namespace.</param>
    /// <param name="containingTypeNames">The names of the ancestor types, outermost first.</param>
    /// <param name="typeName">The union root's own simple name.</param>
    /// <param name="arity">The union root's type parameter count; 0 for a non-generic root.</param>
    /// <param name="suffix">The part identifying which generated file this is, e.g. <c>"g"</c> or <c>"Union.g"</c>.</param>
    private static string BuildHintName(string @namespace,
                                        IEnumerable<string> containingTypeNames,
                                        string typeName,
                                        int arity,
                                        string suffix)
    {
        var segments = new List<string>();

        if (!string.IsNullOrEmpty(@namespace))
        {
            segments.Add(@namespace);
        }

        segments.AddRange(containingTypeNames);

        segments.Add(arity > 0 ? $"{typeName}_{arity}" : typeName);

        var sanitized = SanitizeHintNameSegment(string.Join(".", segments));

        return $"{sanitized}.{suffix}.cs";
    }

    private static string SanitizeHintNameSegment(string value)
    {
        var sb = new StringBuilder(value.Length);
        foreach (var c in value)
        {
            sb.Append(char.IsLetterOrDigit(c) || c is '_' or '.' ? c : '_');
        }
        return sb.ToString();
    }

    // ---- IUnion<T1..T8> path ------------------------------------------------

    /// <summary>
    /// Walks a type symbol's containing-type chain, outermost first, capturing enough about each
    /// ancestor to re-emit its opening declaration line so a generated partial can be nested back
    /// inside it. Empty when <paramref name="type"/> is not a nested type.
    /// </summary>
    /// <param name="type">The type symbol whose ancestors to walk.</param>
    private static ImmutableArray<ContainingTypeInfo> GetContainingTypeChain(INamedTypeSymbol type)
    {
        var chain = new List<ContainingTypeInfo>();

        for (var current = type.ContainingType; current is not null; current = current.ContainingType)
        {
            var typeParameters = current.TypeParameters.Length == 0
                ? string.Empty
                : "<" + string.Join(", ", current.TypeParameters.Select(p => p.Name)) + ">";

            chain.Add(new ContainingTypeInfo(GetTypeDeclarationKeyword(current), current.Name, typeParameters));
        }

        chain.Reverse();
        return chain.ToImmutableArray();
    }

    /// <summary>
    /// The declaration keyword(s) for a type symbol - <c>class</c>, <c>record</c>,
    /// <c>record struct</c>, or <c>struct</c> - as needed to re-declare a matching partial.
    /// </summary>
    /// <param name="type">The type symbol to inspect.</param>
    private static string GetTypeDeclarationKeyword(INamedTypeSymbol type)
        => (type.IsRecord, type.TypeKind) switch
        {
            (true, TypeKind.Struct) => "record struct",
            (true, _) => "record",
            (false, TypeKind.Struct) => "struct",
            (false, TypeKind.Interface) => "interface",
            _ => "class"
        };

    /// <summary>
    /// Reduces a type to the form the CLR actually sees, so that two case types compare equal
    /// exactly when they would produce colliding metadata signatures. Tuple element names are a
    /// source-only, compiler-synthesized annotation (via <see cref="System.Runtime.CompilerServices.TupleElementNamesAttribute"/>)
    /// that <see cref="SymbolEqualityComparer"/> still distinguishes; stripping only the
    /// outermost tuple's names (via <see cref="INamedTypeSymbol.TupleUnderlyingType"/>) is not
    /// enough, because a tuple nested inside another tuple's type arguments — or inside any other
    /// generic type's type arguments — keeps its own element names even after the outer
    /// substitution. This recurses through every generic type argument so nested tuples are
    /// stripped at every level, e.g. both <c>(int X, (int A, int B) Y)</c> and
    /// <c>(int Row, (int C, int D) Col)</c> canonicalize to the same
    /// <c>ValueTuple&lt;int, ValueTuple&lt;int, int&gt;&gt;</c>. Non-tuple, non-generic types
    /// (and generic types with no tuple anywhere in their arguments) are returned unchanged, so
    /// this can never make two genuinely different CLR types compare equal - only ever collapses
    /// distinctions that tuple element names introduce.
    /// </summary>
    /// <param name="type">The type to canonicalize.</param>
    private static ITypeSymbol GetCanonicalClrType(ITypeSymbol type)
    {
        if (type is not INamedTypeSymbol named) { return type; }

        // A tuple's TupleUnderlyingType is itself IsTupleType == true in Roslyn (the unnamed
        // ValueTuple<...> instantiation is still "a tuple type", just without friendly element
        // names) - recursing back through GetCanonicalClrType on it would recurse forever. Strip
        // the name layer at most once per level, then fall through to the general generic-type
        // branch below to canonicalize its type arguments (which is what actually reaches any
        // nested tuple).
        var underlying = named.IsTupleType ? named.TupleUnderlyingType ?? named : named;

        if (underlying.IsGenericType && underlying.TypeArguments.Length > 0)
        {
            var canonicalArguments = underlying.TypeArguments
                .Select(GetCanonicalClrType)
                .ToArray();

            // Reconstructing with unchanged arguments returns an equivalent symbol, so it is safe
            // to always go through Construct rather than special-casing "nothing changed".
            return underlying.ConstructedFrom.Construct(canonicalArguments);
        }

        return underlying;
    }

    /// <summary>
    /// Finds the wrapper (case) names whose case types canonicalize to a CLR type shared with at
    /// least one other case, in declaration order, for UNION009's message.
    /// </summary>
    /// <param name="info">The resolved union model to inspect.</param>
    private static IEnumerable<string> GetCasesSharingAClrType(UnionInfo info)
    {
        var canonical = info.CaseTypes.Select(GetCanonicalClrType).ToArray();

        var duplicatedClrTypes = canonical
            .GroupBy(t => t, SymbolEqualityComparer.Default)
            .Where(g => g.Count() > 1)
            .Select(g => g.Key)
            .ToImmutableHashSet(SymbolEqualityComparer.Default);

        for (var i = 0; i < canonical.Length; i++)
        {
            if (duplicatedClrTypes.Contains(canonical[i]))
            {
                yield return info.CaseNames[i];
            }
        }
    }

    /// <summary>
    /// Reads the <c>[UnionCaseName&lt;T&gt;("...")]</c> overrides declared on a union root.
    /// </summary>
    /// <param name="root">The union root type to inspect.</param>
    private static IReadOnlyDictionary<ITypeSymbol, string> ReadCaseNameOverrides(INamedTypeSymbol root)
    {
        var overrides = new Dictionary<ITypeSymbol, string>(SymbolEqualityComparer.Default);

        foreach (var attribute in root.GetAttributes())
        {
            if (attribute.AttributeClass is not { Name: "UnionCaseNameAttribute" } attributeClass) { continue; }
            if (attributeClass.ContainingNamespace?.ToDisplayString() != "Corsinvest.Fx.Functional") { continue; }
            if (attributeClass.TypeArguments.Length != 1) { continue; }
            if (attribute.ConstructorArguments.Length != 1) { continue; }
            if (attribute.ConstructorArguments[0].Value is not string name) { continue; }

            // Keyed on the exact type the attribute names (e.g. the closed stand-in Some<int>).
            // UnionCaseNaming.FindOverride is responsible for the original-definition fallback
            // that lets this match a case type which closes over the root's own type parameter
            // (Some<T>) - see its remarks for why that fallback must not apply unconditionally.
            overrides[attributeClass.TypeArguments[0]] = name;
        }

        return overrides;
    }

    /// <summary>
    /// Emits the generated source for one <c>IUnion&lt;...&gt;</c> declaration.
    /// </summary>
    /// <param name="context">The source production context to add the generated file to.</param>
    /// <param name="info">The resolved union model built by <see cref="BuildUnionInfo"/>.</param>
    private static void GenerateUnion(SourceProductionContext context, UnionInfo info)
    {
        if (info.HasNameCollision)
        {
            context.ReportDiagnostic(Diagnostic.Create(
                CaseNameCollisionDescriptor, info.Location ?? Location.None, info.TypeName));
            return;
        }

        var hasInterfaceCaseType = false;
        foreach (var caseType in info.CaseTypes)
        {
            if (caseType.TypeKind == TypeKind.Interface)
            {
                hasInterfaceCaseType = true;
                context.ReportDiagnostic(Diagnostic.Create(
                    InterfaceCaseTypeDescriptor, info.Location ?? Location.None, info.TypeName, caseType.Name));
            }
        }

        if (hasInterfaceCaseType) { return; }

        if (!info.EmitImplicitConversions)
        {
            var collidingCaseNames = string.Join(", ", GetCasesSharingAClrType(info));

            context.ReportDiagnostic(Diagnostic.Create(
                DuplicateCaseTypeDescriptor, info.Location ?? Location.None, info.TypeName, collidingCaseNames));
        }

        var sb = new StringBuilder();

        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Threading.Tasks;");
        sb.AppendLine();

        if (!string.IsNullOrEmpty(info.Namespace))
        {
            sb.AppendLine($"namespace {info.Namespace};");
            sb.AppendLine();
        }

        // Re-open each ancestor type, outermost first, so a union root nested inside another type
        // lands back inside it instead of becoming a phantom top-level type.
        foreach (var containingType in info.ContainingTypes)
        {
            sb.AppendLine($"public partial {containingType.Keyword} {containingType.Name}{containingType.TypeParameters}");
            sb.AppendLine("{");
        }

        var root = info.TypeName + info.TypeParameters;

        sb.AppendLine($"public abstract partial record {root}");
        sb.AppendLine("{");
        sb.AppendLine($"    private {info.TypeName}() {{ }}");
        sb.AppendLine();

        var qualified = info.CaseTypes
            .Select(t => t.ToDisplayString(FullyQualifiedNoKeywordsFormat))
            .ToImmutableArray();

        // Wrappers
        for (var i = 0; i < info.CaseNames.Length; i++)
        {
            sb.AppendLine($"    public sealed partial record {info.CaseNames[i]}({qualified[i]} Value) : {root};");
        }
        sb.AppendLine();

        // Implicit conversions
        if (info.EmitImplicitConversions)
        {
            for (var i = 0; i < info.CaseNames.Length; i++)
            {
                sb.AppendLine($"    public static implicit operator {root}({qualified[i]} value) => new {info.CaseNames[i]}(value);");
            }
            sb.AppendLine();
        }

        // Is* properties
        foreach (var name in info.CaseNames)
        {
            sb.AppendLine($"    public bool Is{name} => this is {name};");
        }
        sb.AppendLine();

        GenerateMatch(sb, info, qualified, root);
        GenerateTryGet(sb, info, qualified);

        sb.AppendLine("}");

        // Close the ancestor types opened above, innermost first.
        for (var i = 0; i < info.ContainingTypes.Length; i++)
        {
            sb.AppendLine("}");
        }

        // The Task<TRoot> extension class is a separate top-level static class in the same
        // namespace, not nested inside the ancestor chain re-opened above - so, unlike the bare
        // `root` used inside that chain, it needs the containing types back in front of the name
        // to still resolve to the same type (e.g. Outer.Pet, not just Pet).
        var qualifiedRoot = string.Join(".", info.ContainingTypes.Select(t => t.Name).Append(root));
        GenerateUnionExtensions(sb, info, qualified, qualifiedRoot);

        var arity = info.TypeParameters.Length == 0
            ? 0
            : info.TypeParameters.Count(c => c == ',') + 1;

        var hintName = BuildHintName(
            info.Namespace,
            info.ContainingTypes.Select(t => t.Name),
            info.TypeName,
            arity,
            suffix: "Union.g");

        context.AddSource(hintName, sb.ToString());
    }

    /// <summary>
    /// Appends the synchronous (value- and void-returning) and asynchronous (value- and
    /// void-returning) <c>Match</c>/<c>MatchAsync</c> overloads for a generic union.
    /// </summary>
    /// <param name="sb">The source builder to append to.</param>
    /// <param name="info">The union model supplying case names.</param>
    /// <param name="qualified">Fully-qualified case type names, aligned with <paramref name="info"/>'s case names.</param>
    /// <param name="root">The union root type name including type parameters.</param>
    private static void GenerateMatch(StringBuilder sb,
                                      UnionInfo info,
                                      ImmutableArray<string> qualified,
                                      string root)
    {
        // Match with a result
        sb.AppendLine("    public TResult Match<TResult>(");
        for (var i = 0; i < info.CaseNames.Length; i++)
        {
            var comma = i < info.CaseNames.Length - 1 ? "," : string.Empty;
            sb.AppendLine($"        Func<{qualified[i]}, TResult> on{info.CaseNames[i]}{comma}");
        }
        sb.AppendLine("    )");
        sb.AppendLine("        => this switch");
        sb.AppendLine("        {");
        foreach (var name in info.CaseNames)
        {
            sb.AppendLine($"            {name} wrapped => on{name}(wrapped.Value),");
        }
        sb.AppendLine("            _ => throw new InvalidOperationException(\"Invalid union state\")");
        sb.AppendLine("        };");
        sb.AppendLine();

        // Match without a result
        sb.AppendLine("    public void Match(");
        for (var i = 0; i < info.CaseNames.Length; i++)
        {
            var comma = i < info.CaseNames.Length - 1 ? "," : string.Empty;
            sb.AppendLine($"        Action<{qualified[i]}> on{info.CaseNames[i]}{comma}");
        }
        sb.AppendLine("    )");
        sb.AppendLine("    {");
        sb.AppendLine("        switch (this)");
        sb.AppendLine("        {");
        foreach (var name in info.CaseNames)
        {
            sb.AppendLine($"            case {name} wrapped: on{name}(wrapped.Value); break;");
        }
        sb.AppendLine("            default: throw new InvalidOperationException(\"Invalid union state\");");
        sb.AppendLine("        }");
        sb.AppendLine("    }");
        sb.AppendLine();

        // Async match
        sb.AppendLine("    public async Task<TResult> MatchAsync<TResult>(");
        for (var i = 0; i < info.CaseNames.Length; i++)
        {
            var comma = i < info.CaseNames.Length - 1 ? "," : string.Empty;
            sb.AppendLine($"        Func<{qualified[i]}, Task<TResult>> on{info.CaseNames[i]}{comma}");
        }
        sb.AppendLine("    )");
        sb.AppendLine("        => this switch");
        sb.AppendLine("        {");
        foreach (var name in info.CaseNames)
        {
            sb.AppendLine($"            {name} wrapped => await on{name}(wrapped.Value),");
        }
        sb.AppendLine("            _ => throw new InvalidOperationException(\"Invalid union state\")");
        sb.AppendLine("        };");
        sb.AppendLine();

        // Async match, void-returning
        sb.AppendLine("    public async Task MatchAsync(");
        for (var i = 0; i < info.CaseNames.Length; i++)
        {
            var comma = i < info.CaseNames.Length - 1 ? "," : string.Empty;
            sb.AppendLine($"        Func<{qualified[i]}, Task> on{info.CaseNames[i]}{comma}");
        }
        sb.AppendLine("    )");
        sb.AppendLine("    {");
        sb.AppendLine("        switch (this)");
        sb.AppendLine("        {");
        foreach (var name in info.CaseNames)
        {
            sb.AppendLine($"            case {name} wrapped: await on{name}(wrapped.Value); break;");
        }
        sb.AppendLine("            default: throw new InvalidOperationException(\"Invalid union state\");");
        sb.AppendLine("        }");
        sb.AppendLine("    }");
        sb.AppendLine();
    }

    /// <summary>
    /// Appends one <c>TryGetX</c> method per case type for a generic union.
    /// </summary>
    /// <param name="sb">The source builder to append to.</param>
    /// <param name="info">The union model supplying case names.</param>
    /// <param name="qualified">Fully-qualified case type names, aligned with <paramref name="info"/>'s case names.</param>
    private static void GenerateTryGet(StringBuilder sb,
                                       UnionInfo info,
                                       ImmutableArray<string> qualified)
    {
        for (var i = 0; i < info.CaseNames.Length; i++)
        {
            var name = info.CaseNames[i];
            sb.AppendLine($"    public bool TryGet{name}(out {qualified[i]} value)");
            sb.AppendLine("    {");
            sb.AppendLine($"        if (this is {name} wrapped) {{ value = wrapped.Value; return true; }}");
            sb.AppendLine("        value = default!;");
            sb.AppendLine("        return false;");
            sb.AppendLine("    }");
            sb.AppendLine();
        }
    }

    /// <summary>
    /// Appends the <c>{Root}UnionExtensions</c> static class: three <c>MatchAsync</c> overloads on
    /// <c>Task&lt;TRoot&gt;</c> so fluent async pipelines can match directly on a pending union
    /// without an intermediate <c>await</c> - async handlers returning <c>Task&lt;TResult&gt;</c>,
    /// async handlers returning <c>Task</c>, and sync handlers returning <c>TResult</c>. Each
    /// overload just awaits the task and forwards to the matching instance member.
    /// </summary>
    /// <param name="sb">The source builder to append to.</param>
    /// <param name="info">The union model supplying case names and the root's own type parameters.</param>
    /// <param name="qualified">Fully-qualified case type names, aligned with <paramref name="info"/>'s case names.</param>
    /// <param name="root">The union root type name including type parameters.</param>
    private static void GenerateUnionExtensions(StringBuilder sb,
                                                UnionInfo info,
                                                ImmutableArray<string> qualified,
                                                string root)
    {
        // The extension class needs the root's own type parameters (if any) plus, for the first
        // overload, an additional TResult - e.g. "<T, E, TResult>" for ResultOf<T, E>.
        var rootTypeParams = info.TypeParameters.Length == 0
            ? Array.Empty<string>()
            : info.TypeParameters.Trim('<', '>').Split(',').Select(p => p.Trim()).ToArray();

        string TypeParamList(bool withResult)
        {
            var all = withResult ? rootTypeParams.Append("TResult") : rootTypeParams;
            var list = string.Join(", ", all);
            return list.Length == 0 ? string.Empty : $"<{list}>";
        }

        // Prefix with the containing-type chain so two same-named nested roots in the same
        // namespace (e.g. Outer1.Pet and Outer2.Pet) don't both try to emit a top-level
        // PetUnionExtensions and collide (CS0101) - the extension class itself is never nested,
        // unlike the wrapper types, so it has no other scoping to fall back on.
        var extensionsClassName = string.Concat(info.ContainingTypes.Select(t => t.Name).Append(info.TypeName)) + "UnionExtensions";

        sb.AppendLine($"public static class {extensionsClassName}");
        sb.AppendLine("{");

        // 1) Async handlers returning Task<TResult>
        sb.AppendLine($"    public static async Task<TResult> MatchAsync{TypeParamList(withResult: true)}(");
        sb.AppendLine($"        this Task<{root}> task,");
        for (var i = 0; i < info.CaseNames.Length; i++)
        {
            var comma = i < info.CaseNames.Length - 1 ? "," : string.Empty;
            sb.AppendLine($"        Func<{qualified[i]}, Task<TResult>> on{info.CaseNames[i]}{comma}");
        }
        sb.AppendLine("    )");
        sb.AppendLine("    {");
        sb.AppendLine("        var result = await task;");
        sb.AppendLine("        return await result.MatchAsync(");
        for (var i = 0; i < info.CaseNames.Length; i++)
        {
            var comma = i < info.CaseNames.Length - 1 ? "," : string.Empty;
            sb.AppendLine($"            on{info.CaseNames[i]}{comma}");
        }
        sb.AppendLine("        );");
        sb.AppendLine("    }");
        sb.AppendLine();

        // 2) Async handlers returning Task (void)
        sb.AppendLine($"    public static async Task MatchAsync{TypeParamList(withResult: false)}(");
        sb.AppendLine($"        this Task<{root}> task,");
        for (var i = 0; i < info.CaseNames.Length; i++)
        {
            var comma = i < info.CaseNames.Length - 1 ? "," : string.Empty;
            sb.AppendLine($"        Func<{qualified[i]}, Task> on{info.CaseNames[i]}{comma}");
        }
        sb.AppendLine("    )");
        sb.AppendLine("    {");
        sb.AppendLine("        var result = await task;");
        sb.AppendLine("        await result.MatchAsync(");
        for (var i = 0; i < info.CaseNames.Length; i++)
        {
            var comma = i < info.CaseNames.Length - 1 ? "," : string.Empty;
            sb.AppendLine($"            on{info.CaseNames[i]}{comma}");
        }
        sb.AppendLine("        );");
        sb.AppendLine("    }");
        sb.AppendLine();

        // 3) Sync handlers returning TResult
        sb.AppendLine($"    public static async Task<TResult> MatchAsync{TypeParamList(withResult: true)}(");
        sb.AppendLine($"        this Task<{root}> task,");
        for (var i = 0; i < info.CaseNames.Length; i++)
        {
            var comma = i < info.CaseNames.Length - 1 ? "," : string.Empty;
            sb.AppendLine($"        Func<{qualified[i]}, TResult> on{info.CaseNames[i]}{comma}");
        }
        sb.AppendLine("    )");
        sb.AppendLine("    {");
        sb.AppendLine("        var result = await task;");
        sb.AppendLine("        return result.Match(");
        for (var i = 0; i < info.CaseNames.Length; i++)
        {
            var comma = i < info.CaseNames.Length - 1 ? "," : string.Empty;
            sb.AppendLine($"            on{info.CaseNames[i]}{comma}");
        }
        sb.AppendLine("        );");
        sb.AppendLine("    }");
        sb.AppendLine("}");
        sb.AppendLine();
    }

}