namespace Corsinvest.Fx.CompileTime.Models;

/// <summary>
/// A serializable container for diagnostic data generated by the CompileTime MSBuild Task.
/// </summary>
public class TaskDiagnosticData
{
    /// <summary>
    /// The unique ID of the DiagnosticDescriptor (e.g., "COMPTIME101").
    /// </summary>
    public string Id { get; set; } = string.Empty;

    /// <summary>
    /// The arguments for the message format string.
    /// </summary>
    public object[] MessageArgs { get; set; } = [];

    /// <summary>
    /// The absolute path to the file where the diagnostic should be reported.
    /// </summary>
    public string FilePath { get; set; } = string.Empty;

    /// <summary>
    /// The starting position of the text span to highlight.
    /// </summary>
    public int StartPosition { get; set; }

    /// <summary>
    /// The length of the text span to highlight.
    /// </summary>
    public int Length { get; set; }
}
